export const LONG_REQUEST = 'LONG_REQUEST'
export const LONG_REQUEST_SUCCESS = 'LONG_REQUEST_SUCCESS'
export const OTHER_REQUEST = 'OTHER_REQUEST'
export const OTHER_REQUEST_SUCCESS = 'OTHER_REQUEST_SUCCESS'
